version: '3.8'

services:

  init:
    image: breakthewall/commit
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    entrypoint: sh -c "
        npm init
     && commitizen init cz-conventional-changelog --save-dev --save-exact"

  commit:
    image: breakthewall/commit
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $HOME/.gitconfig:/etc/gitconfig:ro
      - $PWD:$PWD
    working_dir: $PWD
    entrypoint: git cz -am
